apiVersion: v1
kind: Service
metadata:
  name: emp-springboot-service
  namespace: abhijeet
spec: 
  selector:
    app: emp-springboot-app
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

