apiVersion: v1
kind: Service
metadata: 
  name: angular-emp-service
  namespace: abhijeet
spec: 
 selector: 
   app: employee-app
 ports: 
 - protocol: TCP
   port: 80
   targetPort: 80
   nodePort: 31003
 type: NodePort
