apiVersion: v1
kind: Service
metadata: 
  name: emp-mysql-service
  namespace: abhijeet
spec: 
  selector:
    app: emp-mysql-app
  ports: 
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
